// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(PlayersDBContext))]
    [Migration("20220511134313_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BussinesLayer.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BussinesLayer.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Game")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Game");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BussinesLayer.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<int?>("Player")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("Player");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BussinesLayer.Genre", b =>
                {
                    b.HasOne("BussinesLayer.Game", null)
                        .WithMany("Genre_ID")
                        .HasForeignKey("Game");
                });

            modelBuilder.Entity("BussinesLayer.Player", b =>
                {
                    b.HasOne("BussinesLayer.Game", null)
                        .WithMany("Player_ID")
                        .HasForeignKey("Player");

                    b.HasOne("BussinesLayer.Genre", null)
                        .WithMany("Player_ID")
                        .HasForeignKey("Player");
                });

            modelBuilder.Entity("BussinesLayer.Game", b =>
                {
                    b.Navigation("Genre_ID");

                    b.Navigation("Player_ID");
                });

            modelBuilder.Entity("BussinesLayer.Genre", b =>
                {
                    b.Navigation("Player_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
